import { db } from "@/src/db";
import { createGoal, getAllGoals, getGoalById, updateGoal } from "@/src/db/repository/goal";
type Goal = { id: string; title: string; description?: string | null; targetAmount: number; savedAmount: number; targetDate?: number | null; isCompleted: boolean | number };
type CreateGoalData = Parameters<typeof createGoal>[0];
export async function createGoalService(data:CreateGoalData){return createGoal(data);}
export async function addMoneyToGoal(goalId:string,amount:number,accountId:string,categoryId:string){try{await db.withExclusiveTransactionAsync(async()=>{const goal=await getGoalById(goalId);if(!goal)throw new Error("Goal not found");const savedAmount=goal.savedAmount+amount;await updateGoal(goalId,{title:goal.title,description:goal.description??undefined,targetAmount:goal.targetAmount,savedAmount,targetDate:goal.targetDate??undefined,isCompleted:savedAmount>=goal.targetAmount});await import("./transactionService").then(m=>m.addTransactionInTransaction({title:`Savings: ${goal.title}`,amount,type:"expense",accountId,categoryId,note:"Added to goal",transactionDate:Date.now()}));});}catch(error){throw new Error(`Unable to add money to goal: ${String(error)}`);}}
export async function withdrawMoneyFromGoal(goalId:string,amount:number,accountId:string,categoryId:string){try{await db.withExclusiveTransactionAsync(async()=>{const goal=await getGoalById(goalId);if(!goal)throw new Error("Goal not found");const savedAmount=Math.max(0,goal.savedAmount-amount);await updateGoal(goalId,{title:goal.title,description:goal.description??undefined,targetAmount:goal.targetAmount,savedAmount,targetDate:goal.targetDate??undefined,isCompleted:false});await import("./transactionService").then(m=>m.addTransactionInTransaction({title:`Withdrawn from: ${goal.title}`,amount,type:"income",accountId,categoryId,note:"Withdrawn from goal",transactionDate:Date.now()}));});}catch(error){throw new Error(`Unable to withdraw money from goal: ${String(error)}`);}}
export async function getGoalProgress(goalId:string){try{const goal=await getGoalById(goalId);if(!goal)throw new Error("Goal not found");return goal.targetAmount===0?0:(goal.savedAmount/goal.targetAmount)*100;}catch(error){throw new Error(`Unable to get goal progress: ${String(error)}`);}}
export async function getCompletedGoals(){try{return (await getAllGoals() as Goal[]).filter((goal)=>Boolean(goal.isCompleted));}catch(error){throw new Error(`Unable to get completed goals: ${String(error)}`);}}
export async function getActiveGoals(){try{return (await getAllGoals() as Goal[]).filter((goal)=>!goal.isCompleted);}catch(error){throw new Error(`Unable to get active goals: ${String(error)}`);}}
export async function getTotalGoalSavings(){try{return (await getAllGoals() as Goal[]).reduce((sum,goal)=>sum+goal.savedAmount,0);}catch(error){throw new Error(`Unable to get total goal savings: ${String(error)}`);}}
