import React, { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useRouter } from "expo-router";
import { getItem, saveItem } from "@/src/lib/storage";
import { STORAGE_KEYS } from "@/src/constants/storageKeys";
import type { AIProviderName } from "@/src/ai/providers";
const providers: Array<{ id: AIProviderName; label: string; key: string }> = [
  { id: "gemini", label: "Google Gemini", key: STORAGE_KEYS.AI_API_KEY_GEMINI }, { id: "anthropic", label: "Anthropic Claude", key: STORAGE_KEYS.AI_API_KEY_ANTHROPIC }, { id: "openai", label: "OpenAI", key: STORAGE_KEYS.AI_API_KEY_OPENAI }, { id: "xai", label: "xAI Grok", key: STORAGE_KEYS.AI_API_KEY_XAI },
];
export default function AISettingsScreen() {
  const router = useRouter(); const [provider, setProvider] = useState<AIProviderName>("gemini"); const [key, setKey] = useState("");
  useEffect(() => { void (async () => { const selected = await getItem(STORAGE_KEYS.AI_PROVIDER); const next = providers.some((item) => item.id === selected) ? selected as AIProviderName : "gemini"; setProvider(next); setKey((await getItem(providers.find((item) => item.id === next)!.key)) || ""); })(); }, []);
  const choose = async (next: AIProviderName) => { setProvider(next); setKey((await getItem(providers.find((item) => item.id === next)!.key)) || ""); };
  const save = async () => { if (!key.trim()) return Alert.alert("API key required", "Enter a key or choose another provider."); await saveItem(providers.find((item) => item.id === provider)!.key, key.trim()); await saveItem(STORAGE_KEYS.AI_PROVIDER, provider); Alert.alert("Saved", "AI provider updated."); };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.title}>AI settings</Text><Text style={styles.subtitle}>Keys use the device secure store. A server proxy is recommended for production deployments.</Text><Text style={styles.label}>Provider</Text>{providers.map((item) => <Pressable key={item.id} style={[styles.provider, provider === item.id && styles.selected]} onPress={() => void choose(item.id)}><Text style={provider === item.id ? styles.selectedText : styles.providerText}>{item.label}</Text></Pressable>)}<Text style={styles.label}>API key</Text><TextInput value={key} onChangeText={setKey} secureTextEntry autoCapitalize="none" autoCorrect={false} style={styles.input} placeholder="Paste your provider key" /><Pressable style={styles.save} onPress={() => void save()}><Text style={styles.saveText}>Save provider</Text></Pressable><Text style={styles.note}>Keys are never logged. Runtime testing requires credentials and network access.</Text></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#F8F9FB" }, content: { padding: 22 }, back: { color: "#0B1D3A", fontWeight: "700" }, title: { marginTop: 24, fontSize: 32, fontWeight: "800", color: "#0B1D3A" }, subtitle: { marginTop: 8, lineHeight: 20, color: "#6B7280" }, label: { marginTop: 24, marginBottom: 8, color: "#8A93A6", fontSize: 11, fontWeight: "700", textTransform: "uppercase" }, provider: { backgroundColor: "#FFFFFF", padding: 15, borderRadius: 12, marginBottom: 8 }, selected: { backgroundColor: "#0B1D3A" }, providerText: { color: "#0B1D3A", fontWeight: "700" }, selectedText: { color: "#FFFFFF", fontWeight: "700" }, input: { backgroundColor: "#FFFFFF", borderRadius: 12, padding: 14, color: "#0B1D3A" }, save: { marginTop: 24, backgroundColor: "#0B1D3A", borderRadius: 12, padding: 15, alignItems: "center" }, saveText: { color: "#FFFFFF", fontWeight: "800" }, note: { marginTop: 18, color: "#9CA3AF", fontSize: 12, lineHeight: 18 } });
