import React, { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Pressable, SectionList, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import Ionicons from "@expo/vector-icons/Ionicons";
import { useRouter } from "expo-router";
import { getNotifications, markAllNotificationsRead, markNotificationRead, type AppNotification } from "@/src/db/repository/notification";

const icons: Record<string, any> = { bills: "calendar-outline", budgets: "pie-chart-outline", goals: "flag-outline", loans: "cash-outline", insurance: "shield-checkmark-outline", transactions: "receipt-outline", ai_insights: "sparkles-outline", system: "information-circle-outline" };
function sections(items: AppNotification[]) {
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const current = items.filter((item) => item.createdAt >= today.getTime());
  const earlier = items.filter((item) => item.createdAt < today.getTime());
  return [{ title: "TODAY", data: current }, ...(earlier.length ? [{ title: "EARLIER", data: earlier }] : [])];
}
export default function NotificationsScreen() {
  const router = useRouter(); const [items, setItems] = useState<AppNotification[]>([]); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setItems(await getNotifications()); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const open = async (item: AppNotification) => { await markNotificationRead(item.id); setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, isRead: 1 } : entry)); if (item.actionRoute) { let params: Record<string, string> | undefined; try { params = item.actionParams ? JSON.parse(item.actionParams) : undefined; } catch { params = undefined; } router.push({ pathname: item.actionRoute as any, params }); } };
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={() => router.back()}><Ionicons name="arrow-back" size={22} color="#0B1D3A" /></Pressable><Text style={styles.title}>Notifications</Text><Pressable onPress={async () => { await markAllNotificationsRead(); await load(); }}><Text style={styles.mark}>Mark all read</Text></Pressable></View>{loading ? <View style={styles.empty}><ActivityIndicator color="#0B1D3A" /></View> : <SectionList sections={sections(items)} keyExtractor={(item) => item.id} contentContainerStyle={items.length ? styles.list : styles.empty} renderSectionHeader={({ section }) => <Text style={styles.section}>{section.title}</Text>} renderItem={({ item }) => <Pressable style={({ pressed }) => [styles.card, !item.isRead && styles.unread, pressed && styles.pressed]} onPress={() => void open(item)}><View style={styles.icon}><Ionicons name={icons[item.category] || icons.system} size={20} color="#0B1D3A" /></View><View style={styles.copy}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.description}>{item.description}</Text><Text style={styles.time}>{new Date(item.createdAt).toLocaleString("en-IN", { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" })}</Text></View>{!item.isRead && <View style={styles.dot} />}</Pressable>} ListEmptyComponent={<Text style={styles.emptyText}>You’re all caught up.</Text>} />}</SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#F8F9FB" }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 20, paddingTop: 10, paddingBottom: 18 }, title: { fontSize: 22, fontWeight: "800", color: "#0B1D3A" }, mark: { color: "#0B1D3A", fontSize: 12, fontWeight: "700" }, list: { paddingHorizontal: 20, paddingBottom: 30 }, section: { marginTop: 14, marginBottom: 10, color: "#8A93A6", fontSize: 11, fontWeight: "700", letterSpacing: 1 }, card: { flexDirection: "row", alignItems: "flex-start", backgroundColor: "#FFFFFF", borderRadius: 16, padding: 14, marginBottom: 10 }, unread: { backgroundColor: "#FFF8E1" }, pressed: { opacity: 0.7 }, icon: { width: 38, height: 38, borderRadius: 19, backgroundColor: "#EEF2F8", alignItems: "center", justifyContent: "center" }, copy: { flex: 1, marginLeft: 12 }, cardTitle: { color: "#0B1D3A", fontWeight: "800" }, description: { color: "#5F6675", marginTop: 4, lineHeight: 18 }, time: { color: "#9CA3AF", fontSize: 11, marginTop: 7 }, dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: "#EF4444", marginTop: 5 }, empty: { flex: 1, alignItems: "center", justifyContent: "center", padding: 30 }, emptyText: { color: "#7B8190" } });
