import { randomUUID } from "expo-crypto";
import { db } from "../index";
type BillInput={title:string;amount:number;dueDate:number;Frequency?:string;isSubscription?:boolean;categoryId?:string;accountId?:string;notes?:string};
const columns="id,title,amount,dueDate,frequency,is_paid AS isPaid,is_subscription AS isSubscription,category_id AS categoryId,account_id AS accountId,notes,created_at AS createdAt,updated_at AS updatedAt";
export async function createBill(data:BillInput,tx:any=db){try{const now=Date.now();await tx.runAsync("INSERT INTO bills (id,title,amount,dueDate,frequency,is_paid,is_subscription,category_id,account_id,notes,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",randomUUID(),data.title,data.amount,data.dueDate,data.Frequency??null,0,data.isSubscription?1:0,data.categoryId??null,data.accountId??null,data.notes??null,now,now);}catch(error){throw new Error(`Unable to create bill: ${String(error)}`);}}
export async function getBillById(id:string,tx:any=db){try{return await tx.getFirstAsync(`SELECT ${columns} FROM bills WHERE id=?`,id);}catch(error){throw new Error(`Unable to fetch bill: ${String(error)}`);}}
export async function getAllBills(tx:any=db){try{return await tx.getAllAsync(`SELECT ${columns} FROM bills ORDER BY dueDate`);}catch(error){throw new Error(`Unable to fetch bills: ${String(error)}`);}}
export async function updateBill(id:string,data:BillInput,tx:any=db){try{await tx.runAsync("UPDATE bills SET title=?,amount=?,dueDate=?,frequency=?,is_subscription=?,category_id=?,account_id=?,notes=?,updated_at=? WHERE id=?",data.title,data.amount,data.dueDate,data.Frequency??null,data.isSubscription?1:0,data.categoryId??null,data.accountId??null,data.notes??null,Date.now(),id);}catch(error){throw new Error(`Unable to update bill: ${String(error)}`);}}
export async function deleteBill(id:string,tx:any=db){try{await tx.runAsync("DELETE FROM bills WHERE id=?",id);}catch(error){throw new Error(`Unable to delete bill: ${String(error)}`);}}
export async function markBillAsPaid(id:string,tx:any=db){try{await tx.runAsync("UPDATE bills SET is_paid=1,updated_at=? WHERE id=?",Date.now(),id);}catch(error){throw new Error(`Unable to mark bill paid: ${String(error)}`);}}
