import { randomUUID } from "expo-crypto";
import { db } from "../index";
import type { DetectedTransaction } from "@/src/types/models";

const columns = "d.id,d.source,d.source_package AS sourcePackage,d.source_app AS sourceApp,d.raw_text AS rawText,d.merchant,d.amount,d.type,d.transaction_date AS transactionDate,d.account_id AS accountId,d.transfer_to_account_id AS transferToAccountId,d.category_id AS categoryId,d.reference_id AS referenceId,d.account_hint AS accountHint,d.upi_handle AS upiHandle,d.parser,d.parser_version AS parserVersion,d.confidence,d.status,d.duplicate_of AS duplicateOf,d.note,d.created_at AS createdAt,d.updated_at AS updatedAt,c.name AS categoryName";
export type DetectedInput = Omit<DetectedTransaction, "id" | "createdAt" | "updatedAt" | "categoryName"> & { id?: string };
export async function createDetectedTransaction(data: DetectedInput, tx: any = db) { const id = data.id ?? randomUUID(); const now = Date.now(); await tx.runAsync(`INSERT INTO detected_transactions (id,source,source_package,source_app,raw_text,merchant,amount,type,transaction_date,account_id,transfer_to_account_id,category_id,reference_id,account_hint,upi_handle,parser,parser_version,confidence,status,duplicate_of,note,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`, id,data.source,data.sourcePackage??null,data.sourceApp??null,data.rawText,data.merchant??null,data.amount,data.type,data.transactionDate,data.accountId??null,data.transferToAccountId??null,data.categoryId??null,data.referenceId??null,data.accountHint??null,data.upiHandle??null,data.parser??null,data.parserVersion??null,data.confidence,data.status,data.duplicateOf??null,data.note??null,now,now); return id; }
export async function getDetectedTransactions(status?: string, tx:any=db) { return tx.getAllAsync(`${"SELECT " + columns} FROM detected_transactions d LEFT JOIN categories c ON c.id=d.category_id ${status ? "WHERE d.status=?" : ""} ORDER BY d.transaction_date DESC`, ...(status ? [status] : [])); }
export async function getDetectedById(id:string,tx:any=db) { return tx.getFirstAsync(`SELECT ${columns} FROM detected_transactions d LEFT JOIN categories c ON c.id=d.category_id WHERE d.id=?`,id); }
export async function updateDetectedTransaction(id:string, data: Partial<DetectedInput>, tx:any=db) { const allowed: Record<string,string> = { merchant:"merchant",amount:"amount",type:"type",transactionDate:"transaction_date",accountId:"account_id",transferToAccountId:"transfer_to_account_id",categoryId:"category_id",note:"note",status:"status",duplicateOf:"duplicate_of" }; const entries=Object.entries(data).filter(([key,value])=>allowed[key]&&value!==undefined); if (!entries.length) return; await tx.runAsync(`UPDATE detected_transactions SET ${entries.map(([key])=>`${allowed[key]}=?`).join(",")},updated_at=? WHERE id=?`,...entries.map(([,value])=>value===null?null:value),Date.now(),id); }
export async function findDetectedDuplicate(data: Pick<DetectedInput,"referenceId"|"merchant"|"amount"|"type"|"transactionDate"|"accountId">, tx:any=db) { if (data.referenceId) { const row=await tx.getFirstAsync(`SELECT id FROM detected_transactions WHERE reference_id=? AND status NOT IN ('deleted','duplicate')`,data.referenceId); if(row)return {id:row.id,confidence:1}; const ledgerReference=await tx.getFirstAsync(`SELECT id FROM transactions WHERE capture_reference_id=?`,data.referenceId); if(ledgerReference)return {id:ledgerReference.id,confidence:1}; } const ledger=await tx.getFirstAsync(`SELECT id FROM transactions WHERE amount=? AND type=? AND account_id=? AND transaction_date BETWEEN ? AND ? AND lower(title)=lower(?)`,data.amount,data.type,data.accountId??"",data.transactionDate-120000,data.transactionDate+120000,data.merchant??""); if(ledger)return {id:ledger.id,confidence:0.85}; const row=await tx.getFirstAsync(`SELECT id FROM detected_transactions WHERE amount=? AND type=? AND (? IS NULL OR account_id=?) AND transaction_date BETWEEN ? AND ? AND merchant IS NOT NULL AND merchant=? AND status NOT IN ('deleted','duplicate')`,data.amount,data.type,data.accountId??null,data.accountId??null,data.transactionDate-120000,data.transactionDate+120000,data.merchant??""); return row ? {id:row.id,confidence:0.8} : null; }
