import { randomUUID } from "expo-crypto";
import { db } from "../index";
type LoanInput={title:string;principal:number;interestRate:number;monthlyAmount:number;remainingAmount:number;totalMonths:number;paidMonths:number;status:string};
const columns="id,title,principal,interest_rate AS interestRate,monthly_amount AS monthlyAmount,remaining_amount AS remainingAmount,total_months AS totalMonths,paid_months AS paidMonths,status,created_at AS createdAt,updated_at AS updatedAt";
export async function createLoan(data:LoanInput,tx:any=db){try{const now=Date.now();await tx.runAsync("INSERT INTO loans (id,title,principal,interest_rate,monthly_amount,remaining_amount,total_months,paid_months,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)",randomUUID(),data.title,data.principal,data.interestRate,data.monthlyAmount,data.remainingAmount,data.totalMonths,data.paidMonths,data.status,now,now);}catch(error){throw new Error(`Unable to create loan: ${String(error)}`);}}
export async function getLoanById(id:string,tx:any=db){try{return await tx.getFirstAsync(`SELECT ${columns} FROM loans WHERE id=?`,id);}catch(error){throw new Error(`Unable to fetch loan: ${String(error)}`);}}
export async function getAllLoans(tx:any=db){try{return await tx.getAllAsync(`SELECT ${columns} FROM loans ORDER BY created_at DESC`);}catch(error){throw new Error(`Unable to fetch loans: ${String(error)}`);}}
export async function updateLoans(id:string,data:LoanInput,tx:any=db){try{await tx.runAsync("UPDATE loans SET title=?,principal=?,interest_rate=?,monthly_amount=?,remaining_amount=?,total_months=?,paid_months=?,status=?,updated_at=? WHERE id=?",data.title,data.principal,data.interestRate,data.monthlyAmount,data.remainingAmount,data.totalMonths,data.paidMonths,data.status,Date.now(),id);}catch(error){throw new Error(`Unable to update loan: ${String(error)}`);}}
export async function deleteLoans(id:string,tx:any=db){try{await tx.runAsync("DELETE FROM loans WHERE id=?",id);}catch(error){throw new Error(`Unable to delete loan: ${String(error)}`);}}
export async function payEmi(id:string,tx:any=db){const loan=await getLoanById(id,tx);if(!loan)return;const remaining=Math.max(0,loan.remainingAmount-loan.monthlyAmount);await tx.runAsync("UPDATE loans SET remaining_amount=?,paid_months=?,status=?,updated_at=? WHERE id=?",remaining,loan.paidMonths+1,remaining<=0?"completed":"active",Date.now(),id);}
