import { randomUUID } from "expo-crypto";
import { db } from "../index";
type TransferInput={fromAccountId:string;toAccountId:string;amount:number;note?:string;transferDate:number};
const columns="id,from_account_id AS fromAccountId,to_account_id AS toAccountId,amount,note,transfer_date AS transferDate,created_at AS createdAt,updated_at AS updatedAt";
export async function createTransfer(data:TransferInput,tx:any=db){try{const now=Date.now();await tx.runAsync("INSERT INTO transfers (id,from_account_id,to_account_id,amount,note,transfer_date,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)",randomUUID(),data.fromAccountId,data.toAccountId,data.amount,data.note??null,data.transferDate,now,now);}catch(error){throw new Error(`Unable to create transfer: ${String(error)}`);}}
export async function getTransferById(id:string,tx:any=db){try{return await tx.getFirstAsync(`SELECT ${columns} FROM transfers WHERE id=?`,id);}catch(error){throw new Error(`Unable to fetch transfer: ${String(error)}`);}}
export async function getAllTransfers(tx:any=db){try{return await tx.getAllAsync(`SELECT ${columns} FROM transfers ORDER BY transfer_date DESC`);}catch(error){throw new Error(`Unable to fetch transfers: ${String(error)}`);}}
export async function updateTransfer(id:string,data:TransferInput,tx:any=db){try{await tx.runAsync("UPDATE transfers SET from_account_id=?,to_account_id=?,amount=?,note=?,transfer_date=?,updated_at=? WHERE id=?",data.fromAccountId,data.toAccountId,data.amount,data.note??null,data.transferDate,Date.now(),id);}catch(error){throw new Error(`Unable to update transfer: ${String(error)}`);}}
export async function deleteTransfer(id:string,tx:any=db){try{await tx.runAsync("DELETE FROM transfers WHERE id=?",id);}catch(error){throw new Error(`Unable to delete transfer: ${String(error)}`);}}
