import { randomUUID } from "expo-crypto";
import { db } from "../index";
type TransactionInput = { title: string; amount: number; type: string; categoryId: string; accountId: string; note?: string; paymentMethod?: string; receiptImage?: string; tags?: string; transactionDate: number };
const columns = "t.id,t.title,t.amount,t.type,t.category_id AS categoryId,t.account_id AS accountId,t.note,t.payment_method AS paymentMethod,t.receipt_image AS receiptImage,t.tags,t.transaction_date AS transactionDate,t.created_at AS createdAt,t.updated_at AS updatedAt,c.name AS categoryName";
export async function createTransaction(data: TransactionInput, tx: any = db) { try { const now=Date.now(); await tx.runAsync("INSERT INTO transactions (id,title,amount,type,category_id,account_id,note,payment_method,receipt_image,tags,transaction_date,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)", randomUUID(),data.title,data.amount,data.type,data.categoryId,data.accountId,data.note??null,data.paymentMethod??null,data.receiptImage??null,data.tags??null,data.transactionDate,now,now); } catch(error) { throw new Error(`Unable to create transaction: ${String(error)}`); } }
export async function getTransactionById(id:string,tx:any=db) { try{return await tx.getFirstAsync(`SELECT ${columns} FROM transactions t LEFT JOIN categories c ON c.id = t.category_id WHERE t.id=?`,id);}catch(error){throw new Error(`Unable to fetch transaction: ${String(error)}`);} }
export async function getAllTransaction(tx:any=db) { try{return await tx.getAllAsync(`SELECT ${columns} FROM transactions t LEFT JOIN categories c ON c.id = t.category_id ORDER BY t.transaction_date DESC`);}catch(error){throw new Error(`Unable to fetch transactions: ${String(error)}`);} }
export async function getRecentTransactions(limit: number = 5, tx:any=db) { try{return await tx.getAllAsync(`SELECT ${columns} FROM transactions t LEFT JOIN categories c ON c.id = t.category_id ORDER BY t.transaction_date DESC LIMIT ?`, limit);}catch(error){throw new Error(`Unable to fetch recent transactions: ${String(error)}`);} }
export async function updateTransaction(id:string,data:TransactionInput,tx:any=db) { try{await tx.runAsync("UPDATE transactions SET title=?,amount=?,type=?,category_id=?,account_id=?,note=?,payment_method=?,receipt_image=?,tags=?,transaction_date=?,updated_at=? WHERE id=?",data.title,data.amount,data.type,data.categoryId,data.accountId,data.note??null,data.paymentMethod??null,data.receiptImage??null,data.tags??null,data.transactionDate,Date.now(),id);}catch(error){throw new Error(`Unable to update transaction: ${String(error)}`);} }
export async function deleteTransaction(id:string,tx:any=db) { try{await tx.runAsync("DELETE FROM transactions WHERE id=?",id);}catch(error){throw new Error(`Unable to delete transaction: ${String(error)}`);} }
